/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  rx231_basic                            */
/*      FILE         :  rx231_basic.c                          */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/


#include "common.h"
#include "crc.h"




//! UART通信時のコマンド受付用バッファ
volatile uint8_t cmd_buf[0x100];



int main(void) {


	// メインループ
	while (1) {



	}
return 0;
}
