/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  rx231_basic                            */
/*      FILE         :  rx231_basic.c                          */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include "iodefine.h"
#include <stdint.h>





int main(void) {

	volatile int a = 0;


	while (1) {


    }
return a;
}
